FROM sdhibit/rpi-raspbian:latest
RUN apt-get -qy update
RUN apt-get -qy install pkg-config libnautilus-extension-dev
RUN apt-get -qy install build-essential
RUN apt-get -qy install python-gtk2
RUN apt-get -qy install python-docutils

VOLUME /nautilus-dropbox
